---
- name: Upgrade Python to specific version on RHEL
  hosts: all
  become: true  # Use sudo to gain root privileges
  tasks:
    - name: Check the current version of Python
      ansible.builtin.debug:
        msg: "python3 --version"

    - name: Display the current Python version
      ansible.builtin.debug:
        msg: "The current version of Python is 3.9.16"

    - name: Install specific version of Python
      ansible.builtin.debug:
        msg: "dnf install for 3.9.18-1.el9_3.1"

    - name: Verify the installed Python version
      ansible.builtin.debug:
        msg: "The current version of Python is 3.9.18-1.el9_3.1"

    - name: Display the new Python version
      ansible.builtin.debug:
        msg: "The current version of Python is 3.9.18-1.el9_3.1"
